import {Producto} from "@/types";

export const API_URL = "https://api.fake-rest.refine.dev";




const now = new Date().toISOString();

export const PRODUCTOS_MOCK: Producto[] = [
    // 🥛 LECHE
    {
        id: 1,
        public_id: crypto.randomUUID(),
        sabor: "Oreo",
        contenido_ml: 300,
        tipo: "leche",
        precio_venta: "23.00",
        costo_produccion_actual: "11.53",
        activo: false,
        creado_en: now,
        actualizado_en: now,
    },
    {
        id: 2,
        public_id: crypto.randomUUID(),
        sabor: "Bubulubu",
        contenido_ml: 300,
        tipo: "leche",
        precio_venta: "23.00",
        costo_produccion_actual: "11.53",
        activo: true,
        creado_en: now,
        actualizado_en: now,
    },
    {
        id: 3,
        public_id: crypto.randomUUID(),
        sabor: "Fresas con crema",
        contenido_ml: 300,
        tipo: "leche",
        precio_venta: "23.00",
        costo_produccion_actual: "11.53",
        activo: true,
        creado_en: now,
        actualizado_en: now,
    },
    {
        id: 4,
        public_id: crypto.randomUUID(),
        sabor: "Cajeta",
        contenido_ml: 300,
        tipo: "leche",
        precio_venta: "23.00",
        costo_produccion_actual: "11.53",
        activo: true,
        creado_en: now,
        actualizado_en: now,
    },
    {
        id: 5,
        public_id: crypto.randomUUID(),
        sabor: "Nutella",
        contenido_ml: 300,
        tipo: "leche",
        precio_venta: "23.00",
        costo_produccion_actual: "11.53",
        activo: true,
        creado_en: now,
        actualizado_en: now,
    },
    {
        id: 6,
        public_id: crypto.randomUUID(),
        sabor: "Mazapán",
        contenido_ml: 300,
        tipo: "leche",
        precio_venta: "23.00",
        costo_produccion_actual: "11.53",
        activo: true,
        creado_en: now,
        actualizado_en: now,
    },

    // 💧 AGUA
    {
        id: 7,
        public_id: crypto.randomUUID(),
        sabor: "Mango natural",
        contenido_ml: 250,
        tipo: "agua",
        precio_venta: "18.00",
        costo_produccion_actual: "5.30",
        activo: true,
        creado_en: now,
        actualizado_en: now,
    },
    {
        id: 8,
        public_id: crypto.randomUUID(),
        sabor: "Mango con Tajín",
        contenido_ml: 250,
        tipo: "agua",
        precio_venta: "18.00",
        costo_produccion_actual: "5.30",
        activo: true,
        creado_en: now,
        actualizado_en: now,
    },
    {
        id: 9,
        public_id: crypto.randomUUID(),
        sabor: "Mango con chamoy",
        contenido_ml: 250,
        tipo: "agua",
        precio_venta: "18.00",
        costo_produccion_actual: "5.30",
        activo: true,
        creado_en: now,
        actualizado_en: now,
    },
    {
        id: 10,
        public_id: crypto.randomUUID(),
        sabor: "Picafresa",
        contenido_ml: 250,
        tipo: "agua",
        precio_venta: "18.00",
        costo_produccion_actual: "5.30",
        activo: true,
        creado_en: now,
        actualizado_en: now,
    },
    {
        id: 11,
        public_id: crypto.randomUUID(),
        sabor: "Fresa natural",
        contenido_ml: 250,
        tipo: "agua",
        precio_venta: "18.00",
        costo_produccion_actual: "5.30",
        activo: false, // ejemplo realista
        creado_en: now,
        actualizado_en: now,
    },
];